import 'dart:convert';
import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../domain/entities/debt.dart';
import '../../domain/entities/enums.dart';
import '../constants/app_constants.dart';
import '../utils/currency_formatter.dart';
import '../utils/date_formatter.dart';
import 'export/file_saver.dart';

/// Generates CSV/PDF bytes — identical on every platform — then hands
/// them to [saveAndShareBytes], which is swapped per platform at compile
/// time (native file + share sheet, or a browser download on web).
class ExportService {
  ExportService._();

  static String _statusLabel(DebtStatus s) {
    switch (s) {
      case DebtStatus.paid:
        return 'Paid';
      case DebtStatus.partiallyPaid:
        return 'Partially Paid';
      case DebtStatus.overdue:
        return 'Overdue';
      case DebtStatus.outstanding:
        return 'Outstanding';
    }
  }

  /// Exports all debts to a CSV file. No interest/APR columns — only
  /// principal, paid, remaining, and dates.
  static Future<String> exportCsv(List<DebtWithDetails> debts) async {
    final rows = <List<String>>[
      ['Person', 'Type', 'Original Amount', 'Currency', 'Paid', 'Remaining', 'Debt Date', 'Due Date', 'Status', 'Notes'],
      for (final d in debts)
        [
          d.person.name,
          d.debt.type == DebtType.lent ? 'Lent' : 'Borrowed',
          d.debt.originalAmount.toStringAsFixed(2),
          d.debt.currency,
          d.totalPaid.toStringAsFixed(2),
          d.remainingAmount.toStringAsFixed(2),
          DateFormatter.short(d.debt.debtDate),
          DateFormatter.short(d.debt.dueDate),
          _statusLabel(d.status),
          d.debt.description ?? '',
        ],
    ];

    final csv = _toCsv(rows);
    final bytes = Uint8List.fromList(utf8.encode(csv));

    return saveAndShareBytes(
      fileName: 'debt_manager_export.csv',
      bytes: bytes,
      mimeType: 'text/csv',
      shareText: 'Debt Manager — data export',
    );
  }

  /// Exports a single debt to a one-page PDF report, matching the sample
  /// layout in the spec.
  static Future<String> exportDebtPdf(DebtWithDetails item) async {
    final doc = pw.Document();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('DEBT REPORT', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 16),
              _pdfRow('Person', item.person.name),
              _pdfRow('Type', item.debt.type == DebtType.lent ? 'Money Lent' : 'Money Borrowed'),
              _pdfRow('Original Amount', CurrencyFormatter.format(item.debt.originalAmount, item.debt.currency)),
              _pdfRow('Paid', CurrencyFormatter.format(item.totalPaid, item.debt.currency)),
              _pdfRow('Outstanding', CurrencyFormatter.format(item.remainingAmount, item.debt.currency)),
              _pdfRow('Due Date', DateFormatter.medium(item.debt.dueDate)),
              _pdfRow('Status', _statusLabel(item.status)),
              pw.SizedBox(height: 20),
              pw.Text('Payment History:', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              if (item.payments.isEmpty)
                pw.Text('No payments recorded yet.')
              else
                pw.Table(
                  border: pw.TableBorder.all(width: 0.5, color: PdfColors.grey400),
                  columnWidths: const {0: pw.FlexColumnWidth(2), 1: pw.FlexColumnWidth(2), 2: pw.FlexColumnWidth(3)},
                  children: [
                    pw.TableRow(children: [
                      _pdfCell('Date', bold: true),
                      _pdfCell('Amount', bold: true),
                      _pdfCell('Notes', bold: true),
                    ]),
                    for (final p in item.payments)
                      pw.TableRow(children: [
                        _pdfCell(DateFormatter.medium(p.paymentDate)),
                        _pdfCell(CurrencyFormatter.format(p.amount, item.debt.currency)),
                        _pdfCell(p.notes ?? '—'),
                      ]),
                  ],
                ),
              pw.Spacer(),
              pw.Divider(),
              pw.Text(AppConstants.shariahDisclaimer, style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
              pw.SizedBox(height: 4),
              pw.Text('Generated by Debt Manager', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
            ],
          );
        },
      ),
    );

    final bytes = await doc.save();

    return saveAndShareBytes(
      fileName: 'debt_report_${item.person.name}.pdf',
      bytes: bytes,
      mimeType: 'application/pdf',
      shareText: 'Shariah Debt Report — ${item.person.name}',
    );
  }

  static pw.Widget _pdfRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        children: [
          pw.SizedBox(width: 130, child: pw.Text(label, style: const pw.TextStyle(color: PdfColors.grey700))),
          pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  static pw.Widget _pdfCell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text, style: pw.TextStyle(fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal, fontSize: 10)),
    );
  }

  /// Minimal RFC-4180-style CSV encoder — avoids depending on the `csv`
  /// package, whose API can shift between major versions. Quotes any
  /// field containing a comma, quote, or newline, doubling inner quotes.
  static String _toCsv(List<List<String>> rows) {
    String escapeField(String field) {
      final needsQuoting = field.contains(',') || field.contains('"') || field.contains('\n') || field.contains('\r');
      if (!needsQuoting) return field;
      return '"${field.replaceAll('"', '""')}"';
    }

    return rows.map((row) => row.map(escapeField).join(',')).join('\r\n');
  }
}
